language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

# Build
script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./reverseproxy

# Tagging
  - docker tag udagram-api-user dnlatt/udagram-api-user:v1
  - docker tag udagram-api-feed dnlatt/udagram-api-feed:v1
  - docker tag udagram-frontend dnlatt/udagram-frontend:v1
  - docker tag reverseproxy dnlatt/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dnlatt/udagram-api-user:v1
  - docker push dnlatt/udagram-api-feed:v1
  - docker push dnlatt/udagram-frontend:v1
  - docker push dnlatt/reverseproxy:v1