language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t udagram-reverseproxy ./udagram-reverseproxy
- docker tag udagram-api-feed dnlatt/udagram-api-feed:v2
- docker tag udagram-api-user dnlatt/udagram-api-user:v2
- docker tag udagram-frontend dnlatt/udagram-frontend:v2
- docker tag udagram-reverseproxy dnlatt/udagram-reverseproxy:v2

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push dnlatt/udagram-api-feed:v2
- docker push dnlatt/udagram-api-user:v2
- docker push dnlatt/udagram-frontend:v2
- docker push dnlatt/udagram-reverseproxy:v2
